name: test workflow

on: push

jobs:
  test:
    runs-on: windows-11-arm

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.13.0'
          - '3.13.1'
          - '3.13.2'
          - '3.13.3'
          - '3.13.4'
          - '3.x'

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -VV
      - run: |
          python -c 'import sys; print("gil?", getattr(sys, "_is_gil_enabled", lambda: None)())'
      - run: python -m pip install cffi
